# Generated by Django 5.1 on 2024-08-31 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('msgTime', models.TimeField(auto_now_add=True)),
                ('msgdate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
